"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['localTest.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'app.icns',
           'plist': {
               'CFBundleName': 'LocalTest',  # 应用名
               'CFBundleDisplayName': 'LocalTest',  # 应用显示名
               'CFBundleVersion': '1.1.0',  # 应用版本号
               'CFBundleIdentifier': 'lt',  # 应用包名、唯一标识
               'NSHumanReadableCopyright': 'Copyright © 2023 Bob Bao. All rights reserved.',  # 可读版权
           }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
