"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['login.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'app.icns',
           'plist': {
               'CFBundleName': 'MoeGo Login Tool',  # 应用名
               'CFBundleDisplayName': 'MoeGo Login Tool',  # 应用显示名
               'CFBundleVersion': '1.0.0',  # 应用版本号
               'CFBundleIdentifier': 'mlt',  # 应用包名、唯一标识
           }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
